### ISSUE TITLE
TesseractPHP? How about TesseractJava?

### ISSUE THREAD

**Issue by Pizzahaet** [TesseractTeam/TesseractPHP#4]
I like PHP in all but wouldn't it make more sense to make this version of Tesseract in Java because Java is basically what MCPE is coded in and Java client to Php to server doesn't make to much sense to me seems like the problem of all these issue's are caused because of this. I could be wrong though but it just make's more sense to make the software in Java.

**Comment by Thunder33345** [comment]
I dont think MCPE is in java only MCPC is in java
My opinion is, the idea of matching what client is coded in should me what server is coded it makes no sense is a misconception, there's not a lot of reasons you want to match it up, you can say matching it up make things smoother BUT that only make sense if the current langue is worse off and it make no sense IF the current language is faster, isnt it to some level pointless + more things to learn

**Comment by AppleDevelops** [comment]
MCPE is in C++ on all devices but Android and iOS include their own stuff in it. I could be wrong though
